const util = require('util')
const logger = require('../../../utils/logger')
const sqlInstance = require('../../../database/mysql')
const moment = require("moment")
const { Op, fn, col } = require('sequelize')
